'use client';
import {useEffect,useState} from 'react';
import {createClient} from '../lib/supabase/client';

type SessionRow={id:string;started_at:string;completed_at:string|null;score:number|null;passed:boolean|null;critical_error_count:number;student_id:string;metadata:Record<string,unknown>;scenarios?:{scenario_key?:string;version?:number;title?:string}|null};
type AttemptRow={id:string;turn_index:number;attempt_index:number;transcript:string|null;score:any;created_at:string};

const configured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

export default function InstructorDashboard(){
 const [sessions,setSessions]=useState<SessionRow[]>([]);const [attempts,setAttempts]=useState<AttemptRow[]>([]);const [selected,setSelected]=useState<string>();const [status,setStatus]=useState(configured()?'Loading authenticated review queue…':'Supabase is not configured; no production student data is shown.');
 useEffect(()=>{if(!configured())return;const supabase=createClient();supabase.from('sessions').select('id,started_at,completed_at,score,passed,critical_error_count,student_id,metadata,scenarios(scenario_key,version,title)').order('started_at',{ascending:false}).limit(50).then(({data,error})=>{if(error){setStatus(`Review queue unavailable: ${error.message}`);return}setSessions((data||[]) as unknown as SessionRow[]);setStatus(data?.length?'':'No sessions visible to the authenticated account.')})},[]);
 async function review(id:string){setSelected(id);setAttempts([]);if(!configured())return;const supabase=createClient();const {data,error}=await supabase.from('transmissions').select('id,turn_index,attempt_index,transcript,score,created_at').eq('session_id',id).eq('speaker','student').order('turn_index').order('attempt_index');if(error){setStatus(`Replay unavailable: ${error.message}`);return}setAttempts((data||[]) as AttemptRow[])}
 return <div className="trainer-grid"><section className="card"><h2>Review Queue</h2><p className="small">Live Supabase data appears only when the project is configured and the signed-in account is authorized by RLS.</p>{status&&<p className="small">{status}</p>}{sessions.map(s=><button className="review-row" key={s.id} onClick={()=>review(s.id)}><strong>{s.scenarios?.scenario_key||String(s.metadata?.scenario_key||'Scenario')}</strong><span>{new Date(s.started_at).toLocaleString()}</span><span>{s.score==null?'In progress':`${s.score}%`} · critical {s.critical_error_count}</span></button>)}</section><section className="card"><h2>Transmission Replay</h2>{!selected?<p className="small">Choose a session to inspect every retry and its grading evidence.</p>:attempts.length===0?<p className="small">No student transmissions are visible for this session.</p>:attempts.map(a=><article className="replay" key={a.id}><div className="row"><span className="badge">Turn {a.turn_index+1}</span><span className="badge">Attempt {a.attempt_index}</span><span className="badge">{a.score?.score??'—'}%</span></div><p>“{a.transcript||'No transcript'}”</p><p className="small">Missing: {Array.isArray(a.score?.missing)?a.score.missing.join(', ')||'none':'—'} · source: {a.score?.source||'unknown'} · key-up→score: {a.score?.telemetry?.endToEndMs??'—'} ms</p></article>)}</section></div>;
}
